// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AdminRoles.tsx": () => import("../components/mockups/AdminRoles.tsx"),
  "./components/mockups/AuthLoginFlow.tsx": () => import("../components/mockups/AuthLoginFlow.tsx"),
  "./components/mockups/AutomationMonitor.tsx": () => import("../components/mockups/AutomationMonitor.tsx"),
  "./components/mockups/B2BCompetitor.tsx": () => import("../components/mockups/B2BCompetitor.tsx"),
  "./components/mockups/B2BPitchGenerator.tsx": () => import("../components/mockups/B2BPitchGenerator.tsx"),
  "./components/mockups/CalendarSyncMonitor.tsx": () => import("../components/mockups/CalendarSyncMonitor.tsx"),
  "./components/mockups/ContactTimeline.tsx": () => import("../components/mockups/ContactTimeline.tsx"),
  "./components/mockups/DashboardMobilePolish.tsx": () => import("../components/mockups/DashboardMobilePolish.tsx"),
  "./components/mockups/ExecutiveDashboard.tsx": () => import("../components/mockups/ExecutiveDashboard.tsx"),
  "./components/mockups/LLMJsonReview.tsx": () => import("../components/mockups/LLMJsonReview.tsx"),
  "./components/mockups/MobileInbox.tsx": () => import("../components/mockups/MobileInbox.tsx"),
  "./components/mockups/OperatorPresenceInbox.tsx": () => import("../components/mockups/OperatorPresenceInbox.tsx"),
  "./components/mockups/PreventivoPDFPreview.tsx": () => import("../components/mockups/PreventivoPDFPreview.tsx"),
  "./components/mockups/ProductionHealthCenter.tsx": () => import("../components/mockups/ProductionHealthCenter.tsx"),
  "./components/mockups/TaskBoard.tsx": () => import("../components/mockups/TaskBoard.tsx"),
  "./components/mockups/VoiceCommandReview.tsx": () => import("../components/mockups/VoiceCommandReview.tsx")
};
